HotelManagement/HotelManagement.MVC/Controllers/CustomerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using HotelManagement.Core.ServiceInterfaces;
using HotelManagement.Infrastructure.Services;
using HotelManagement.Core.Entities;
using HotelManagement.Core.Models;
// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace HotelManagement.MVC.Controllers
{
    public class CustomerController : Controller
    {
        private readonly ICustomerService _customerService;

        public CustomerController(ICustomerService customerService)
        {
            _customerService = customerService;
        }

        public async Task<IActionResult> Detail(int id)
        {
            var customer = await _customerService.GetCustomerById(id);
            return View(customer);
        }
        [HttpGet]
        public IActionResult AddCustomer()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> AddCustomer(AddCustomerModel customerModel)
        {
            var createCustomer = await _customerService.AddCustomer(customerModel);
            return LocalRedirect("~/");
        }
        [HttpPost]
        public async Task<IActionResult> UpdateCustomer(AddCustomerModel model)
        {
            if (!ModelState.IsValid)
            {
                return RedirectToAction("AddCustomer");
            }
            var updateCustomer = await _customerService.UpdateCustomer(model.Id, model);
            //redirect to login
            return RedirectToAction("AddCustomer");
        }


        [HttpPost]
        public async Task<IActionResult> DeleteCustomer(AddCustomerModel model)
        {
            if (!ModelState.IsValid)
            {
                return RedirectToAction("AddCustomer");
            }
            await _customerService.DeleteCustomer(model.Id);
            //redirect to login
            return RedirectToAction("AddCustomer");
        }

        public async Task<IActionResult> SearchCustomer(AddCustomerModel model)
        {
            var existCustomer = await _customerService.SearchCustomer(model.Id);
            return View(existCustomer);
        }
    }
}

HotelManagement/HotelManagement.MVC/Controllers/RoomController.cs
using System;
using System.Threading.Tasks;
using HotelManagement.Core.Models;
using HotelManagement.Core.ServiceInterfaces;
using Microsoft.AspNetCore.Mvc;

namespace HotelManagement.MVC.Controllers
{
    public class RoomController : Controller
    {
        private readonly IRoomService _roomService;

        public RoomController(IRoomService roomService)
        {
            _roomService = roomService;
        }
        [HttpGet]
        public IActionResult AddRoom()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> AddRoom(AddRoomModel roomModel)
        {
            var createService = await _roomService.AddRoom(roomModel);
            return LocalRedirect("~/");
        }

        [HttpPost]
        public async Task<IActionResult> UpdateRoom(AddRoomModel model)
        {
            if (!ModelState.IsValid)
            {
                return RedirectToAction("AddRoom");
            }
            var updateRoom = await _roomService.UpdateRoom(model.Id, model);
            //redirect to login
            return RedirectToAction("AddRoom");
        }


        [HttpPost]
        public async Task<IActionResult> DeleteRoom(AddRoomModel model)
        {
            if (!ModelState.IsValid)
            {
                return RedirectToAction("AddRoom");
            }
            await _roomService.DeleteRoom(model.Id);
            //redirect to login
            return RedirectToAction("AddRoom");
        }

        public async Task<IActionResult> SearchRoom(AddRoomModel model)
        {
            var existRoom = await _roomService.SearchRoom(model.Id);
            return View(existRoom);
        }

        public async Task<IActionResult> ListRooms()
        {
            var rooms = await _roomService.GetAllRooms();

            return View(rooms);
        }
    }
}

HotelManagement/HotelManagement.MVC/Controllers/RoomtypeController.cs
using System;
using System.Threading.Tasks;
using HotelManagement.Core.Models;
using HotelManagement.Core.ServiceInterfaces;
using Microsoft.AspNetCore.Mvc;

namespace HotelManagement.MVC.Controllers
{
    public class RoomtypeController : Controller
    {
        private readonly IRoomtypeService _roomtypeService;
        public RoomtypeController(IRoomtypeService roomtypeService)
        {
            _roomtypeService = roomtypeService;
        }

        [HttpGet]
        public IActionResult AddRoomtype()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> AddRoomtype(AddRoomtypeModel roomtypeModel)
        {
            var createService = await _roomtypeService.AddRoomtype(roomtypeModel);
            return LocalRedirect("~/");
        }

        [HttpPost]
        public async Task<IActionResult> UpdateRoomtype(AddRoomtypeModel model)
        {
            if (!ModelState.IsValid)
            {
                return RedirectToAction("AddRoomtype");
            }
            var updateRoomtype = await _roomtypeService.UpdateRoomtype(model.Id,model);
            //redirect to login
            return RedirectToAction("AddRoomtype");
        }


        [HttpPost]
        public async Task<IActionResult> DeleteRoomtype(AddRoomtypeModel model)
        {
            if (!ModelState.IsValid)
            {
                return RedirectToAction("AddRoomtype");
            }
            await _roomtypeService.DeleteRoomtype(model.Id);
            //redirect to login
            return RedirectToAction("AddRoomtype");
        }

        public async Task<IActionResult> SearchRoomtype(AddRoomtypeModel model)
        {
            var existRoomtype = await _roomtypeService.SearchRoomtype(model.Id);
            return View(existRoomtype);
        }


        public async Task<IActionResult> ListRoomtypes()
        {
            var roomtypes = await _roomtypeService.GetAllRoomtypes();

            return View(roomtypes);
        }
    }
}

HotelManagement/HotelManagement.MVC/Controllers/ServiceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using HotelManagement.Core.ServiceInterfaces;
using Microsoft.AspNetCore.Mvc;
using HotelManagement.Core.Models;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace HotelManagement.MVC.Controllers
{
    public class ServiceController : Controller
    {
        private readonly IServiceService _serviceService;

        public ServiceController(IServiceService serviceService)
        {
            _serviceService = serviceService;
        }
        [HttpGet]
        public IActionResult AddService()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> AddService(AddServiceModel serviceModel)
        {
            var createService = await _serviceService.AddService(serviceModel);
            return LocalRedirect("~/");
        }

        [HttpPost]
        public async Task<IActionResult> UpdateService(AddServiceModel model)
        {
            if (!ModelState.IsValid)
            {
                return RedirectToAction("AddService");
            }
            var updateService = await _serviceService.UpdateService(model.Id, model);
            //redirect to login
            return RedirectToAction("AddService");
        }

        [HttpPost]
        public async Task<IActionResult> DeleteService(AddServiceModel model)
        {
            if (!ModelState.IsValid)
            {
                return RedirectToAction("AddService");
            }
            await _serviceService.DeleteService(model.Id);
            //redirect to login
            return RedirectToAction("AddService");
        }

        public async Task<IActionResult> SearchService(AddServiceModel model)
        {
            var existService = await _serviceService.SearchService(model.Id);
            return View(existService);
        }
        public async Task<IActionResult> ListServices()
        {
            var services = await _serviceService.GetAllServices();

            return View(services);
        }
    }
}

HotelManagement/HotelManagement.MVC/Views/Shared/_CustomerCard.cshtml
@model HotelManagement.Core.Entities.Customer

<td>
    <a asp-controller="Customer" asp-action="Detail" asp-route-id="@Model.Id">
        @Model.Id
    </a>
</td>

<td>
    <a asp-controller="Customer" asp-action="Detail" asp-route-id="@Model.Id">
        @Model.CName
    </a>
</td>

<td>
    <a asp-controller="Customer" asp-action="Detail" asp-route-id="@Model.Id">
        @Model.RoomNo
    </a>
</td>
<td>
    <a asp-controller="Customer" asp-action="Detail" asp-route-id="@Model.Checkin">
        @Model.Checkin
    </a>
</td>

HotelManagement/HotelManagement.MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - HotelManagement.MVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Hotel Management System</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Customer" asp-action="AddCustomer">Edit Customer</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Service" asp-action="AddService">Edit Service</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Room" asp-action="AddRoom">Edit Room</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Roomtype" asp-action="AddRoomtype">Edit Roomtype</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Rufeng Ma 07/26/2021 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

HotelManagement/HotelManagement.MVC/Views/Shared/_SearchCustomer.cshtml
@model HotelManagement.Core.Models.CustomerDetailResponseModel

<div class="col-12">
    <h2>Search Customer By Id</h2>
    <div class="input-group">
        <div class="form-outline">

            <a asp-controller="Home" asp-action="SearchCustomer" asp-route-id="@Model.Id">
                <input type="search" id="form1" class="form-control" />
                @Model.Id
            </a>
            <label class="form-label" for="form1"></label>
        </div>
        <button type="button" class="btn btn-primary">
            <i class="fas fa-search"></i>
        </button>
    </div>
</div>